### ISSUE TITLE
Modifying pool with CNTools alpha v7.0.0 fails in hybrid online mode 

### ISSUE THREAD

**Issue by amani1104** [cardano-community/guild-operators#689]
**Describe the bug**
When modifying a pool with CNTools alpha v7.0.0 in hybrid mode, the operation fails with the online client due to missing secret key for the main pledge wallet. Secret keys for all involved wallets are not available on the online machine, as they are stored more safely on the air-gapped machine. 

The operation fails with the following error message:

```
jq: error: Could not open file /opt/cardano/cnode/priv/wallet/BAKE1/payment.skey: No such file or directory
jq: error: syntax error, unexpected '}' (Unix shell quoting issues?) at <top-level>, line 1:
."signing-file" += [{ name: "Owner #1 'letzbake' payment signing key", vkey:  }]                                                                              
jq: 1 compile error
```

**To Reproduce**
1. Select hybrid-mode for modifying the pool
2. Register multi-owner pool and select two or more pledge wallets, one of which was previously registered as the only owner. 
3. Register separate rewards wallet from main owner

**Expected behavior**
The online CNTools client does not look for secret keys, as these are not available on the online machine. The operation is expected to be signed on the air-gapped machine, where secret keys are available.  

**Version:**
 - OS: [Ubuntu 20.04 LTS]
 - Product version: [CNTools v7.0.0 alpha]
 - Cardano Node version: 1.24.2
 - Network you're connecting to: Mainnet

**Comment by Scitz0** [comment]
Good catch 👍  copy&paste mistake. Should be vkey, not skey. 
I'll make a quick patch.

**Comment by Scitz0** [comment]
Fixed in #691, please update using prereqs.sh as the same version is reused. Internal update won't detect the updated version.

**Comment by amani1104** [comment]
Yes, the issue is not resolved. However, I opened a new issue #692 that is related to the same operation as this issue.
